version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

grpc:
  listen: tcp://0.0.0.0:9090
  proto:
    - "proto/auth.proto"
  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

server:
  command: "php grpc-worker.php"
  relay: pipes
