<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto

namespace App\Grpc\Auth\Metadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xCE\x02\x0A\x0Aauth.proto\x12\x04auth\"\$\x0A\x0CTokenRequest\x12\x14\x0A\x0Caccess_token\x18\x01 \x01(\x09\"\x9A\x01\x0A\x0CUserResponse\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\x12\x0C\x0A\x04name\x18\x02 \x01(\x09\x12\x0D\x0A\x05email\x18\x03 \x01(\x09\x12\x0B\x0A\x03uid\x18\x04 \x01(\x09\x12\x19\x0A\x11email_verified_at\x18\x05 \x01(\x09\x12\x12\x0A\x0Acreated_at\x18\x06 \x01(\x09\x12\x12\x0A\x0Aupdated_at\x18\x07 \x01(\x09\x12\x11\x0A\x09fcm_token\x18\x08 \x01(\x092D\x0A\x0BAuthService\x125\x0A\x0BVerifyToken\x12\x12.auth.TokenRequest\x1A\x12.auth.UserResponseB)\xCA\x02\x0DApp\\Grpc\\Auth\xE2\x02\x16App\\Grpc\\Auth\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

