<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace App\Grpc\Auth;

use Spiral\RoadRunner\GRPC;

interface AuthServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "auth.AuthService";

    /**
     * @param GRPC\ContextInterface $ctx
     * @param TokenRequest $in
     * @return UserResponse
     *
     * @throws GRPC\Exception\InvokeException
     */
    public function VerifyToken(GRPC\ContextInterface $ctx, TokenRequest $in): UserResponse;
}
