<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto

namespace App\Grpc\Auth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>auth.UserResponse</code>
 */
class UserResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string email = 3;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string uid = 4;</code>
     */
    protected $uid = '';
    /**
     * On utilise string pour les formats ISO8601
     *
     * Generated from protobuf field <code>string email_verified_at = 5;</code>
     */
    protected $email_verified_at = '';
    /**
     * Generated from protobuf field <code>string created_at = 6;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 7;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>string fcm_token = 8;</code>
     */
    protected $fcm_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $name
     *     @type string $email
     *     @type string $uid
     *     @type string $email_verified_at
     *           On utilise string pour les formats ISO8601
     *     @type string $created_at
     *     @type string $updated_at
     *     @type string $fcm_token
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\Auth\Metadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uid = 4;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>string uid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->uid = $var;

        return $this;
    }

    /**
     * On utilise string pour les formats ISO8601
     *
     * Generated from protobuf field <code>string email_verified_at = 5;</code>
     * @return string
     */
    public function getEmailVerifiedAt()
    {
        return $this->email_verified_at;
    }

    /**
     * On utilise string pour les formats ISO8601
     *
     * Generated from protobuf field <code>string email_verified_at = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEmailVerifiedAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->email_verified_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 6;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 7;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fcm_token = 8;</code>
     * @return string
     */
    public function getFcmToken()
    {
        return $this->fcm_token;
    }

    /**
     * Generated from protobuf field <code>string fcm_token = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFcmToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->fcm_token = $var;

        return $this;
    }

}

